services:
  frontend:
    build:
      context: ./devtoolbox
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./devtoolbox:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development