services:
  frontend:
    build:
<<<<<<< HEAD
      context: ./devtoolbox
=======
      context: ./app
>>>>>>> ab09fa2a4dbd14223f3074570fb8993bf88be172
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
<<<<<<< HEAD
      - ./devtoolbox:/app
=======
      - ./app:/app
>>>>>>> ab09fa2a4dbd14223f3074570fb8993bf88be172
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
<<<<<<< HEAD
      - NODE_ENV=development
=======
      - NODE_ENV=development
>>>>>>> ab09fa2a4dbd14223f3074570fb8993bf88be172
